version: '3.8'

services:
  templater:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./templates:/app/templates
      - ./output:/app/output
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "templater", "--version"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped 